# Generated by Django 2.2.6 on 2019-12-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pehchan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('sex', models.CharField(choices=[('F', 'Woman'), ('M', 'Male'), ('L', 'Others')], max_length=1)),
            ],
        ),
    ]
