# Generated by Django 2.2.6 on 2019-12-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pehchan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('sex', models.CharField(choices=[('F', 'Woman'), ('M', 'Male'), ('L', 'Others')], max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='pehchan',
        ),
    ]
