# Generated by Django 2.2.6 on 2019-12-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pehchan', '0002_auto_20191218_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='unique_no',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
    ]
