# Generated by Django 2.2.6 on 2019-12-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pehchan', '0003_users_unique_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='unique_no',
            field=models.IntegerField(verbose_name=123),
        ),
    ]
