# Generated by Django 2.2.6 on 2019-12-26 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelance_basic',
            old_name='date',
            new_name='Date',
        ),
    ]
