# Generated by Django 2.2.9 on 2020-01-04 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custom_user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
