# Generated by Django 2.2.9 on 2020-01-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts2', '0002_auto_20200104_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=50, unique=True),
        ),
    ]
