# Generated by Django 2.2.9 on 2020-01-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts2', '0004_auto_20200104_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='central_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('DOB', models.DateField(default='auto_now=True')),
                ('username', models.CharField(max_length=50)),
                ('number', models.IntegerField(default='8055504914')),
                ('sex', models.BooleanField(choices=[('M', 'male'), ('F', 'female')], default='Male')),
            ],
        ),
    ]
