# Generated by Django 2.2.9 on 2020-01-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts2', '0005_central_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
