# Generated by Django 2.2.9 on 2020-01-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts2', '0006_auto_20200104_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='full_name',
            field=models.CharField(default='vaibhav subhash patil', max_length=50),
            preserve_default=False,
        ),
    ]
