# Generated by Django 2.2.6 on 2020-01-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
    ]
