# Generated by Django 2.2.6 on 2020-01-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200101_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='email',
            field=models.EmailField(default='abc123@gmail.com', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
