# Generated by Django 2.2.6 on 2020-01-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200101_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='custom_user',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='full_name',
            field=models.CharField(default='vaibhav subhash patil', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custom_user',
            name='phone',
            field=models.IntegerField(default=8055504914, unique=True),
            preserve_default=False,
        ),
    ]
