# Generated by Django 2.2.6 on 2020-01-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200101_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
