# Generated by Django 2.2.6 on 2020-01-01 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200101_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='email',
        ),
    ]
