# Generated by Django 2.2.6 on 2020-01-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_custom_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='logged_in',
        ),
        migrations.AddField(
            model_name='custom_user',
            name='email',
            field=models.EmailField(default=8055504914, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='DOB',
            field=models.DateField(null=True),
            preserve_default=False,
        ),
    ]
