# Generated by Django 2.2.6 on 2020-01-01 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200101_2142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Custom_User',
        ),
    ]
