# Generated by Django 2.2.9 on 2020-01-01 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_custom_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='users',
            name='DOB',
        ),
    ]
