# Generated by Django 2.2.9 on 2020-01-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200101_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='DOB',
            field=models.DateField(null=True),
        ),
    ]
