# Generated by Django 2.2.9 on 2020-01-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200101_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
        migrations.RemoveField(
            model_name='users',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='users',
            name='unique_no',
        ),
        migrations.AddField(
            model_name='custom_user',
            name='gender',
            field=models.CharField(choices=[('F', 'Woman'), ('M', 'Male'), ('L', 'Others')], default='male', max_length=1),
            preserve_default=False,
        ),
    ]
