# Generated by Django 2.2.9 on 2020-01-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200102_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='timestamd',
            field=models.DateTimeField(auto_now_add=True, default='1998-11-18 12:35'),
            preserve_default=False,
        ),
    ]
